name       : xapp
version    : 2.6.1
release    : 3
source     :
    - https://github.com/linuxmint/xapp/archive/refs/tags/2.6.1.tar.gz : c16c633c5c7ea572d7db77be9f0fdaa57c7b9f335a62f5fcb6b87bf6473aff0f
license    : LGPL-3.0-or-later
component  : desktop.library
summary    : Cross-desktop libraries and common resources
description: |
    This project gathers the components which are common to multiple GTK desktop environments (Cinnamon, MATE and Xfce) and required to implement cross-DE solutions.
builddeps  :
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(pygobject-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
