name       : xapp
version    : 2.4.2
release    : 1
source     :
    - https://github.com/linuxmint/xapp/archive/refs/tags/2.4.2.tar.gz : b01c5037f0da773bc822f32c98c7281fd1cf5b9bc9c0e7cbf8eb2c38d0661b4d
license    : LGPL-3.0-or-later
component  : desktop.library
summary    : Cross-desktop libraries and common resources
description: |
    This project gathers the components which are common to multiple GTK desktop environments (Cinnamon, MATE and Xfce) and required to implement cross-DE solutions.
builddeps  :
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(pygobject-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
