name       : xapp
version    : 2.4.3
release    : 2
source     :
    - https://github.com/linuxmint/xapp/archive/refs/tags/2.4.3.tar.gz : f544c2ed1902803f524fc13aaf38e1b7f6c1fa9770ca6ab2bd9306e7385b01a9
license    : LGPL-3.0-or-later
component  : desktop.library
summary    : Cross-desktop libraries and common resources
description: |
    This project gathers the components which are common to multiple GTK desktop environments (Cinnamon, MATE and Xfce) and required to implement cross-DE solutions.
builddeps  :
    - pkgconfig(dbusmenu-gtk3-0.4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(pygobject-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
